server:
  port: 8089

spring:
  application:
      name: source-zipkin
  output:
    ansi:
      enabled: ALWAYS
  zipkin:
    base-url: http://192.168.65.0:9411/
  sleuth:
    sampler:
      probability: 0.1

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/